//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
    Hash,
)]
#[sea_orm(table_name = "project_relations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub project: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub dependency: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub kind: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project_version_refs::Entity",
        from = "Column::Dependency",
        to = "super::project_version_refs::Column::Value",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProjectVersionRefs,
    #[sea_orm(
        belongs_to = "super::project_versions::Entity",
        from = "Column::Project",
        to = "super::project_versions::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProjectVersions,
}

impl Related<super::project_version_refs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectVersionRefs.def()
    }
}

impl Related<super::project_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
