//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use super::sea_orm_active_enums::VisibilityEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
    Hash,
)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub readme: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub source: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub issues: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub wiki: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub downloads: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub license: Option<String>,
    pub visibility: VisibilityEnum,
    pub tags: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gallery_images::Entity")]
    GalleryImages,
    #[sea_orm(has_many = "super::moderation_comment::Entity")]
    ModerationComment,
    #[sea_orm(has_many = "super::moderation_queue::Entity")]
    ModerationQueue,
    #[sea_orm(has_many = "super::project_authors::Entity")]
    ProjectAuthors,
    #[sea_orm(has_many = "super::project_versions::Entity")]
    ProjectVersions,
}

impl Related<super::gallery_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GalleryImages.def()
    }
}

impl Related<super::moderation_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModerationComment.def()
    }
}

impl Related<super::moderation_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModerationQueue.def()
    }
}

impl Related<super::project_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectAuthors.def()
    }
}

impl Related<super::project_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectVersions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_authors::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_authors::Relation::Projects.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
