//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
    Hash,
)]
#[sea_orm(table_name = "project_versions")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub project: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub version_number: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
    pub loaders: Vec<String>,
    pub game_versions: Vec<String>,
    pub downloads: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project_relations::Entity")]
    ProjectRelations,
    #[sea_orm(has_one = "super::project_version_refs::Entity")]
    ProjectVersionRefs,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::Project",
        to = "super::projects::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Projects,
    #[sea_orm(has_many = "super::version_files::Entity")]
    VersionFiles,
}

impl Related<super::project_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectRelations.def()
    }
}

impl Related<super::project_version_refs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectVersionRefs.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::version_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VersionFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
