//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
    Hash,
)]
#[sea_orm(table_name = "project_repo_syncs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub project_id: i32,
    #[sea_orm(column_type = "Text")]
    pub repo_owner: String,
    #[sea_orm(column_type = "Text")]
    pub repo_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_branch: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub webhook_secret: String,
    pub sync_readme: bool,
    pub sync_releases: bool,
    pub sync_faq: bool,
    pub sync_links: bool,
    pub last_push_sync_at: Option<DateTime>,
    pub last_release_sync_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Projects,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
