//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
    Hash,
    strum_macros :: Display,
    strum_macros :: EnumString,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "moderation_status_enum"
)]
pub enum ModerationStatusEnum {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "denied")]
    Denied,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "under_review")]
    UnderReview,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
    Hash,
    strum_macros :: Display,
    strum_macros :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "visibility_enum")]
pub enum VisibilityEnum {
    #[sea_orm(string_value = "public")]
    Public,
    #[sea_orm(string_value = "private")]
    Private,
    #[sea_orm(string_value = "unlisted")]
    Unlisted,
}
