//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
    Hash,
)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub username: String,
    pub github_id: i32,
    pub admin: bool,
    pub moderator: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::moderation_comment::Entity")]
    ModerationComment,
    #[sea_orm(has_many = "super::moderation_queue::Entity")]
    ModerationQueue,
    #[sea_orm(has_many = "super::project_authors::Entity")]
    ProjectAuthors,
    #[sea_orm(has_many = "super::user_tokens::Entity")]
    UserTokens,
}

impl Related<super::moderation_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModerationComment.def()
    }
}

impl Related<super::moderation_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModerationQueue.def()
    }
}

impl Related<super::project_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectAuthors.def()
    }
}

impl Related<super::user_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTokens.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_authors::Relation::Projects.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_authors::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
