//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
    utoipa :: ToResponse,
    Hash,
)]
#[sea_orm(table_name = "version_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    #[sea_orm(column_type = "Text")]
    pub sha1: String,
    #[sea_orm(column_type = "Text")]
    pub s3_id: String,
    pub size: i64,
    pub version_id: i32,
    pub uploaded_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project_versions::Entity",
        from = "Column::VersionId",
        to = "super::project_versions::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProjectVersions,
}

impl Related<super::project_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
